<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<ProjectType>ProgramLibrary</ProjectType>
	</PropertyGroup>
	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<RootNamespace>PepperDash.Essentials.Plugin.Bluesound.Api</RootNamespace>
		<Deterministic>false</Deterministic>
		<AssemblyTitle>PepperDash.Essentials.Plugin.Bluesound.Api</AssemblyTitle>
		<Company>PepperDash Technology</Company>
		<Description>This software is a PepperDash Essentials Plugin for the Bluesound API.</Description>
		<Copyright>Copyright © 2026 PepperDash Technology</Copyright>
		<Version>1.0.0-local</Version>
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
		<InformationalVersion>$(Version)</InformationalVersion>
		<OutputPath>bin\$(Configuration)\</OutputPath>
		<Authors>PepperDash Technology</Authors>
		<PackageId>Pepperdash.Essentials.Plugins.Bluesound.Api</PackageId>
		<PackageProjectUrl>https://github.com/PepperDash/epi-bluesound-api.git</PackageProjectUrl>
		<PackageTags>crestron 4series essentials plugin bluesound api</PackageTags>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DefineConstants>$(DefineConstants);SERIES4</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Properties\**" />
		<EmbeddedResource Remove="Properties\**" />
		<None Remove="Properties\**" />
	</ItemGroup>

	<ItemGroup>
    <None Remove="epi-make-model.projectinfo" />
  </ItemGroup>

  <ItemGroup>
 	<PackageReference Include="PepperDashEssentials" Version="2.28.1">
  		<ExcludeAssets>runtime</ExcludeAssets>
 	</PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Remove="../output\epi-bluesound-api.4Series.1.0.0-local.cplz" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="../output\epi-bluesound-api.4Series.1.0.0-local.cplz" />
  </ItemGroup>
</Project>
